name: tachidesk_sorayomi
description: A new Flutter frontend for Tachidesk.

publish_to: "none"
version: 0.3.6+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.2
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  easy_localization: ^3.0.1
  file_picker: ^5.2.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  fluttertoast: ^8.1.1
  font_awesome_flutter: ^10.2.1
  freezed_annotation: ^2.2.0
  go_router: ^6.0.0
  hooks_riverpod: ^2.1.1
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  package_info_plus: ^3.0.1
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  pub_semver: ^2.1.2
  riverpod_annotation: ^1.0.6
  scrollable_positioned_list: ^0.3.5
  share_plus: ^6.2.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.6
  web_socket_channel: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.2
  # flutter_flavorizr: ^2.1.5
  flutter_gen_runner: ^5.1.0+1
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.14
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  lints: ^2.0.1
  riverpod_generator: ^1.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/launcher/
    - assets/locales/

flutter_gen:
  output: lib/src/constants/gen/

flutter_native_splash:
  color: "#54C5F8"
  image: assets/icons/dark_icon.png
  branding: assets/icons/launcher/from_suwayomi.png
  color_dark: "#01579B"
  image_dark: assets/icons/light_icon.png
  android_12:
    color: "#54C5F8"
    color_dark: "#01579B"
    icon_background_color: "#54C5F8"
    icon_background_color_dark: "#01579B"
    image: assets/icons/dark_icon.png
    image_dark: assets/icons/light_icon.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/launcher/sorayomi_icon.png"
  web:
    generate: true
    image_path: "assets/icons/launcher/sorayomi_icon.png"
    background_color: "#54C5F8"
    theme_color: "#54C5F8"
  windows:
    generate: true
    image_path: "assets/icons/launcher/sorayomi_icon.png"
  macos:
    generate: true
    image_path: "assets/icons/launcher/sorayomi_icon.png"
